server:
  port: 8641
# 自身服务的名称 注册中心的配置
spring:
  #application:          在bootstrap.yml中已经配置，config是根据bootstrap的name和profile来查找配置
   #name: configClient8641

  cloud:
    consul:
      discovery:
        service-name: configClient8641  # 服务提供者名称
      host: localhost                  # consul 所在服务地址
      port: 8500
